package kr.co.telecons.mconhudsdk.enums

enum class MConHudNotifyType {
    NOTIFY_TYPE_ILLUMINANCE,
    NOTIFY_TYPE_TIME_UPDATE,
    NOTIFY_TYPE_BUZZER_SOUND,
    NOTIFY_TYPE_FIRMWARE_INFO,
    NOTIFY_TYPE_FIRMWARE_UPDATE,
    NOTIFY_TYPE_FIRMWARE_UPDATE_BLOCK,
    NOTIFY_TYPE_FIRMWARE_UPDATE_COMPLETE
}